Flowpack:
  JobQueue:
    Common:
      queues:
        'turboCharger':
          className: 'Flowpack\JobQueue\Common\Queue\FakeQueue'
          options:
            async: true
            executeIsolated: true
